name: test
on:
  push:
    branches:
      - branch/test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: amondnet/vercel-action@v19
        id: vercel-action-dev
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
